field.formatter.settings.eldrich_citation_formatter:
  type: field.formatter.settings.entity_reference_label
  mapping:
    length:
      label: 'Show title as'
      type: string
    destination:
      label: 'Link to'
      type: string
field.formatter.settings.eldrich_popup_formatter:
  type: field.formatter.settings.entity_reference_label
  mapping:
    length:
      label: 'Show title as'
      type: string
field.widget.settings.entity_reference_override_longtext_widget:
  type: field.widget.settings.entity_reference_override_longtext_widget
  mapping:
    types:
      type: sequence
      sequence:
        type: string
        label: 'Content Types'
    delimiter:
      type: string
      label: 'String delimiter'
    short_name:
      type: boolean
      label: 'Search short name'
